###signup
POST http://localhost:3003/signup
Content-Type: application/json

{
    "name": "Alice",
	"email": "alice@lbn.com",
	"password": "123452"
}

###login
POST http://localhost:3003/login
Content-Type: application/json

{
	"email": "alice@lbn.com",
	"password": "123452"
}

###get profile user
GET http://localhost:3003/user/profile
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiJ9.YTRkNWMyMTctMDc1Ni00MGM4LTg3OWMtNmVhYTAxMTg0NWUw.-gkl3xsLAk17ULaEhW5SBgXHh7auGDkX-H0wwjKQDwY

###Create recipes
POST http://localhost:3003/recipe
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiJ9.YTRkNWMyMTctMDc1Ni00MGM4LTg3OWMtNmVhYTAxMTg0NWUw.-gkl3xsLAk17ULaEhW5SBgXHh7auGDkX-H0wwjKQDwY

{
	"title": "título da receita",
	"description": "descrição da receita"
}
