###test request
POST http://localhost:3003/user/signup
Content-Type: application/json

{     "name": "aben",
      "password": "47851269",
      "email": "abn@gmail.com",
      "role": "NORMAL"
}

###test request login
POST http://localhost:3003/login
Content-Type: application/json

{
     "password": "47851269",
      "email": "abn@gmail.com"
}



###get all users 
GET http://localhost:3003/all
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE4N2VlZGRhLTE5Y2ItNDQ3MS1hM2QzLTc3MGU0ZDM4OTU4MiIsInJvbGUiOiJub3JtYWwiLCJpYXQiOjE2MTIyNjY5NDMsImV4cCI6MTYxMjI3MDU0M30.Q37TUsIzP_SRDTHH3DCQy2qOtnFO2tkte-SxyRh-pDE
